name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  source-owner:
    description: 'The GitHub owner (organisation or individual) of the repo to receive artifacts from'
    required: true
  source-repo:
    description: 'The repo (owned by source-owner) to receive artifacts from'
    required: true
  permitted-branches:
    description: 'A list of branches known to be sufficiently protected that artifacts built from them may be republished'
    required: true
    default: 'master'
  package-push-token:
    description: 'A GitHub auth token which has access to upload packages to the repo where the action is running'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
