name: 'check-and-republish-package'
description: 'Checks that a GitHub Artifact produced by a workflow in another repo came from one of a named list of trusted branches. If so, uploads the contents of the Artifact as a GitHub Package'
inputs:
  source-owner:
    description: 'The GitHub owner (organisation or individual) of the repo to accept artifacts from'
    required: true
  source-repo-workflow-branches:
    description: 'A comma-separated list of repo/workflow/branch combinations to search for artifacts'
    required: true
  source-token:
    description: 'A GitHub auth token which has access to read workflow information, including logs and artifacts, from the source owner and repo(s)'
    required: true
  package-push-token:
    description: 'A GitHub auth token which has access to upload packages to the repo where this action is running'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
