on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test check-and-republish-package action
        uses: ./
        with:
          source-owner: djn24
          source-repo: DotNetLib
          permitted-branches: master
          package-push-token: Can't test package push locally anyway
